from __future__ import annotations

import argparse
import base64
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

from PIL import Image


def api_image(prompt: str, base: str, key: str) -> bytes:
    body = json.dumps(
        {
            "model": "gpt-image-2",
            "prompt": prompt,
            "n": 1,
            "size": "1024x1024",
            "response_format": "b64_json",
        }
    ).encode("utf-8")
    request = urllib.request.Request(
        base.rstrip("/") + "/images/generations",
        data=body,
        headers={
            "Authorization": "Bearer " + key,
            "Content-Type": "application/json",
            "Accept": "application/json",
            "User-Agent": "literacy-visual-assets/1.0",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=180) as response:
            payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")[:500]
        raise RuntimeError(f"CliproxAPI HTTP {error.code}: {detail}") from error
    except urllib.error.URLError as error:
        raise RuntimeError(f"CliproxAPI network error: {error.reason}") from error

    if payload.get("error"):
        raise RuntimeError(f"CliproxAPI error: {payload['error']}")
    rows = payload.get("data") or []
    encoded = rows[0].get("b64_json") if rows else None
    if not encoded:
        raise RuntimeError("CliproxAPI response is missing data[0].b64_json")
    try:
        return base64.b64decode(encoded, validate=True)
    except Exception as error:  # pragma: no cover - defensive boundary around remote data
        raise RuntimeError("CliproxAPI returned invalid base64 image data") from error


def chroma_key(raw: bytes) -> Image.Image:
    image = Image.open(__import__("io").BytesIO(raw)).convert("RGBA")
    pixels = image.load()
    for y in range(image.height):
        for x in range(image.width):
            red, green, blue, alpha = pixels[x, y]
            green_distance = green - max(red, blue)
            if green > 185 and green_distance > 60:
                pixels[x, y] = (red, green, blue, 0)
            elif green > 150 and green_distance > 35:
                fade = max(0, min(255, int((green_distance - 35) * 5)))
                pixels[x, y] = (red, green, blue, min(alpha, fade))
    return image


def trim(image: Image.Image, padding: int = 12) -> Image.Image:
    alpha = image.getchannel("A")
    bbox = alpha.getbbox()
    if not bbox:
        return image
    left, top, right, bottom = bbox
    left = max(0, left - padding)
    top = max(0, top - padding)
    right = min(image.width, right + padding)
    bottom = min(image.height, bottom + padding)
    return image.crop((left, top, right, bottom))


def save_raw(raw: bytes, path: Path) -> str:
    if raw[:3] == b"\xff\xd8\xff":
        suffix = ".jpg"
    elif raw[:8] == b"\x89PNG\r\n\x1a\n":
        suffix = ".png"
    else:
        raise RuntimeError("generated bytes are neither PNG nor JPEG")
    raw_path = path.with_suffix(suffix)
    raw_path.write_bytes(raw)
    return raw_path.name


def crop_grid(image: Image.Image, rows: int, cols: int) -> list[Image.Image]:
    tile_width = image.width / cols
    tile_height = image.height / rows
    parts: list[Image.Image] = []
    for row in range(rows):
        for col in range(cols):
            box = (
                round(col * tile_width),
                round(row * tile_height),
                round((col + 1) * tile_width),
                round((row + 1) * tile_height),
            )
            parts.append(trim(image.crop(box)))
    return parts


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--prompt-dir", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args()

    base = (os.environ.get("CLIPROX_API_BASE") or "").strip()
    key = (os.environ.get("CLIPROX_API_KEY") or "").strip()
    if not base or not key:
        raise SystemExit("CLIPROX_API_BASE / CLIPROX_API_KEY must be set in the process environment")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    manifest: dict[str, object] = {
        "schemaVersion": 1,
        "subject": "preschool-literacy-uplift",
        "generator": "gpt-image-2 via CliproxAPI",
        "background": "#00ff00 chroma-key removed",
        "items": [],
    }

    def add_item(asset_id: str, prompt_name: str, image: Image.Image, source_name: str) -> None:
        output = args.out_dir / f"{asset_id}.png"
        image.save(output, format="PNG", optimize=True)
        manifest["items"].append(
            {
                "id": asset_id,
                "file": output.name,
                "source": source_name,
                "prompt": prompt_name,
                "width": image.width,
                "height": image.height,
                "mode": image.mode,
                "alphaCorners": [image.getpixel(point)[3] for point in [(0, 0), (image.width - 1, 0), (0, image.height - 1), (image.width - 1, image.height - 1)]],
            }
        )
        print(f"wrote {output.name} {image.width}x{image.height}")

    prompt = (args.prompt_dir / "companion.txt").read_text(encoding="utf-8").strip()
    raw = api_image(prompt, base, key)
    raw_name = save_raw(raw, args.out_dir / "_raw-companion")
    add_item("literacy-companion-reading", "companion.txt", trim(chroma_key(raw)), raw_name)

    prompt = (args.prompt_dir / "actions-sheet.txt").read_text(encoding="utf-8").strip()
    raw = api_image(prompt, base, key)
    raw_name = save_raw(raw, args.out_dir / "_raw-actions-sheet")
    for asset_id, part in zip(
        ["literacy-action-assess", "literacy-action-mistakes", "literacy-action-profile"],
        crop_grid(chroma_key(raw), 1, 3),
    ):
        add_item(asset_id, "actions-sheet.txt", part, raw_name)

    prompt = (args.prompt_dir / "badges-sheet.txt").read_text(encoding="utf-8").strip()
    raw = api_image(prompt, base, key)
    raw_name = save_raw(raw, args.out_dir / "_raw-badges-sheet")
    for asset_id, part in zip(
        ["literacy-badge-seed", "literacy-badge-story", "literacy-badge-reading", "literacy-badge-fluent"],
        crop_grid(chroma_key(raw), 2, 2),
    ):
        add_item(asset_id, "badges-sheet.txt", part, raw_name)

    prompt = (args.prompt_dir / "certificate-corner.txt").read_text(encoding="utf-8").strip()
    raw = api_image(prompt, base, key)
    raw_name = save_raw(raw, args.out_dir / "_raw-certificate-corner")
    add_item("literacy-certificate-corner", "certificate-corner.txt", trim(chroma_key(raw)), raw_name)

    (args.out_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(f"manifest {args.out_dir / 'manifest.json'}")


if __name__ == "__main__":
    try:
        main()
    except RuntimeError as error:
        print(str(error), file=sys.stderr)
        raise SystemExit(1)
